docker_apt_repository: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian   bookworm stable"
docker_gpg_key_url: "https://download.docker.com/linux/debian/gpg"
